### ISSUE TITLE
AttributeError:'ChSystemNSC' object has no attribute 'SetVisualSystem'

### ISSUE THREAD

**Issue by EQJ1NBJ** [projectchrono/chrono#469]
version: Solidworks2021 chrono 8.0 and Chronosolidworks8.0
question: when do the solidworks demo engine，after click the 'Run test', there is the Error hit:
AttributeError:'ChSystemNSC' object has no attribute 'SetVisualSystem'
![error](https://github.com/projectchrono/chrono/assets/147672679/4d4cf237-1eca-4c85-a29b-6f37bf1c8b49)

**Comment by rserban** [comment]
Could you please confirm that replacing line 198 in `run_test.py` with
`    vis.AttachSystem(my_system)`
fixes the problem?

**Comment by EQJ1NBJ** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hello Serban,
        Thanks for the reply.I have tried as your suggestion, then there appears a new similar error.Wang Nan
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Radu ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/12/2023 13:56
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [projectchrono/chrono] AttributeError:'ChSystemNSC' object has no attribute 'SetVisualSystem' (Issue #469)
        
      
    
  
  
Could you please confirm that replacing line 198 in run_test.py with
    vis.AttachSystem(my_system)
fixes the problem?

**Comment by rserban** [comment]
I'm not sure I follow.  Could you please be more clear in describing whatever issue it is that you are having?

**Comment by EQJ1NBJ** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        sorry for missing the attachment.
        
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Radu ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/12/2023 15:17
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [projectchrono/chrono] AttributeError:'ChSystemNSC' object has no attribute 'SetVisualSystem' (Issue #469)
        
      
    
  
  
I'm not sure I follow.  Could you please be more clear in describing whatever issue it is that you are having?

**Comment by rserban** [comment]
I still don't understand.  What is the problem? What error do you get? Doing what?
What is this snippet:
```
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }
```
supposed to say?

**Comment by rserban** [comment]
@dariofusai93 Do you have any idea what this could be about?!?

**Comment by EQJ1NBJ** [comment]
> @dariofusai93 Do you have any idea what this could be about?!?

I replyed  you with the error picture just now by E-mail.
I just find that you can't see the error picture.
now I put the error picture again here.
![error2](https://github.com/projectchrono/chrono/assets/147672679/56a7c340-9a5d-4a40-82ce-51656a65dad3)

**Comment by rserban** [comment]
OK, that Python script must be fixed (for both errors). We'll do that and will post here when done.

In the future, please just type the error message instead of trying to attach images.

**Comment by rserban** [comment]
There's an updated SolidWorks plugin on the download page on [projectchrono.org](https://projectchrono.org/download/).
Please try installing the new plugin and let us know if this resolves the issue.

**Comment by dariomangoni** [comment]
@EQJ1NBJ please mind that the Solidworks plugin is now fixed and is expected to work fine, but with the **current development version** of Chrono so it is not guaranteed that will work when exporting to the older official binary release of Chrono **8.0**!

**Comment by EQJ1NBJ** [comment]
> There's an updated SolidWorks plugin on the download page on [projectchrono.org](https://projectchrono.org/download/). Please try installing the new plugin and let us know if this resolves the issue.

I have tried to download the Solidworks9.2 on this page mane times, but failed. other version can still be download.

**Comment by rserban** [comment]
I just reorganized how access to the SolidWorks add-in versions is provided.  Please see the updated [download](https://projectchrono.org/download/) page on the project website. 
- a direct link is provided to download the version of the add-in that is compatible with the **current** Chrono development code.
- versions of the add-in compatible with previous Chrono releases are now available from the GitHub Releases page.

Please try to get the new SolidWorks add-in (now called `Chrono_SolidWorks_current.exe`) and let us know if everything works.

**Comment by EQJ1NBJ** [comment]
> I just reorganized how access to the SolidWorks add-in versions is provided. Please see the updated [download](https://projectchrono.org/download/) page on the project website.
> 
> * a direct link is provided to download the version of the add-in that is compatible with the **current** Chrono development code.
> * versions of the add-in compatible with previous Chrono releases are now available from the GitHub Releases page.
> 
> Please try to get the new SolidWorks add-in (now called `Chrono_SolidWorks_current.exe`) and let us know if everything works.

Thanks.
I have tried the current Chronosolidworks  with both Chrono 8.0 and development branch, the 8.0 is not fixed, but the development branch is OK.

**Comment by rserban** [comment]
As I mentioned above, the new SolidWorks add-in is **NOT** compatible with Chrono 8.0
